#!/usr/bin/env python3
"""AgentCore pack installer (Python-first, idempotent)."""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from pack_paths import pack_root  # noqa: E402

from install_support import (  # noqa: E402
    RuntimeMode,
    docker_available,
    gather_interactive_config,
    install_os_dependencies,
    install_systemd_user_units,
    narrative_for_runtime,
    print_banner,
    production_hints,
    start_docker_compose_stack,
    start_docker_postgres,
)
from install_support import run_cmd as support_run_cmd  # noqa: E402

MIN_PYTHON = (3, 12)

DEMO_ENV = """# Generated by scripts/install.py (demo profile). Safe for local judging.
# Full template: .env.example
# Do not commit real credentials.
CHANGE_SOCIETY_ENVIRONMENT=development
CHANGE_SOCIETY_MODEL_PROVIDER=fake
QWEN_API_KEY=
QWEN_MODEL=qwen-plus
CHANGE_SOCIETY_STORE=memory
CHANGE_SOCIETY_CONTEXT_TOKEN_BUDGET=1800
CHANGE_SOCIETY_ALLOWED_ORIGINS=http://localhost:32501
CHANGE_SOCIETY_MANAGED_AGENTS_CONFIG=
CHANGE_SOCIETY_WEBHOOK_AGENT_SECRET=
CHANGE_SOCIETY_WEBHOOK_AGENT_TIMEOUT_SECONDS=30
CHANGE_SOCIETY_API_PORT=32500
NEXT_PUBLIC_CHANGE_SOCIETY_API_URL=http://localhost:32500
NEXT_PUBLIC_CHANGE_SOCIETY_PROJECT_ID=demo-project
NEXT_PUBLIC_CHANGE_SOCIETY_TENANT_ID=demo-tenant
NEXT_PUBLIC_CHANGE_SOCIETY_WORKSPACE_ID=demo-workspace
# Docker full stack (only if --runtime docker):
# AGENTCORE_POSTGRES_PASSWORD=choose-a-strong-local-password
"""


def check_python() -> None:
    if sys.version_info < MIN_PYTHON:
        raise SystemExit(
            f"Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ is required; found {sys.version.split()[0]}."
        )


def run(cmd: list[str], *, cwd: Path | None = None, dry_run: bool = False) -> None:
    support_run_cmd(cmd, dry_run=dry_run, cwd=cwd)


def ensure_venv(pack: Path, dry_run: bool) -> Path:
    venv = pack / ".venv"
    python = venv / "bin" / "python"
    if not python.is_file():
        print(f"Creating virtual environment at {venv}")
        run([sys.executable, "-m", "venv", str(venv)], dry_run=dry_run)
    elif dry_run:
        print(f"Would use existing virtual environment at {venv}")
    else:
        rehome_venv_script_shebangs(venv, python)
    return python


def rehome_venv_script_shebangs(venv: Path, python: Path) -> None:
    """Rewrite #! in venv/bin scripts when the repo path moved (e.g. clone location change)."""
    bin_dir = venv / "bin"
    if not bin_dir.is_dir() or not python.is_file():
        return
    py = python.resolve()
    target = f"#!{py}\n"
    for script in bin_dir.iterdir():
        if not script.is_file() or script.name == "python" or script.name.startswith("python"):
            continue
        try:
            text = script.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if not text.startswith("#!"):
            continue
        first_line, _, rest = text.partition("\n")
        if "python" not in first_line:
            continue
        if first_line + "\n" == target:
            continue
        script.write_text(target + rest, encoding="utf-8")


def install_backend(python: Path, requirements: Path, dry_run: bool) -> None:
    run([str(python), "-m", "pip", "install", "--upgrade", "pip"], dry_run=dry_run)
    run([str(python), "-m", "pip", "install", "-r", str(requirements)], dry_run=dry_run)


def install_frontend(frontend: Path, dry_run: bool, skip: bool) -> None:
    if skip:
        print("Skipping frontend install (--skip-frontend).")
        return
    npm = shutil.which("npm")
    if not npm:
        raise SystemExit(
            "npm not found. Example fixes:\n"
            "  Debian/Ubuntu: bash install.sh --install-os-deps   (uses sudo apt)\n"
            "  Or install Node.js 20+ manually, then re-run: bash install.sh"
        )
    lock = frontend / "package-lock.json"
    if lock.is_file():
        run([npm, "ci"], cwd=frontend, dry_run=dry_run)
    else:
        run([npm, "install"], cwd=frontend, dry_run=dry_run)


def ensure_demo_env(env_path: Path, dry_run: bool) -> None:
    if env_path.is_file():
        print(f"Keeping existing {env_path} (not overwritten).")
        return
    print(f"Writing demo profile to {env_path}")
    if dry_run:
        return
    env_path.write_text(DEMO_ENV, encoding="utf-8")


def run_verify(pack: Path, dry_run: bool) -> None:
    script = pack / "scripts" / "run-real-test.sh"
    if dry_run:
        print(f"Would run {script}")
        return
    run(["bash", str(script)], cwd=pack)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Install AgentCore Change Society demo dependencies.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples (non-interactive):
  bash install.sh
  bash install.sh --non-interactive --profile verify --runtime manual
  bash install.sh --install-os-deps --runtime systemd
  bash install.sh --runtime docker --profile demo
  bash install.sh --with-postgres --non-interactive

Interactive (default on a TTY): numbered menus with examples for profile, OS packages, runtime, optional Postgres.
""",
    )
    parser.add_argument(
        "--profile",
        choices=("demo", "verify", "production"),
        default=None,
        help="demo (default): venv + deps + demo .env; verify: + run-real-test; production: hints only",
    )
    parser.add_argument(
        "--runtime",
        choices=("manual", "systemd", "docker", "none"),
        default=None,
        help="How to run after install. Interactive prompt on TTY if omitted.",
    )
    parser.add_argument(
        "--install-os-deps",
        action="store_true",
        help="Debian/Ubuntu: sudo apt install python venv, nodejs, npm, docker when needed",
    )
    parser.add_argument(
        "--with-postgres",
        action="store_true",
        help="If Docker is available: start deployments/compose.dev-postgres.yaml",
    )
    parser.add_argument(
        "--non-interactive",
        action="store_true",
        help="No prompts; use flags or defaults (profile=demo, runtime=manual)",
    )
    parser.add_argument("--skip-frontend", action="store_true", help="Do not run npm in frontend/.")
    parser.add_argument("--dry-run", action="store_true", help="Print steps without installing.")
    return parser.parse_args()


def resolve_config(args: argparse.Namespace) -> tuple[str, RuntimeMode, bool, bool]:
    interactive = not args.non_interactive and not args.dry_run and sys.stdin.isatty()
    profile = args.profile
    runtime: RuntimeMode | None = args.runtime  # type: ignore[assignment]
    install_os = args.install_os_deps if args.install_os_deps else None
    with_pg = args.with_postgres if args.with_postgres else None

    if interactive:
        return gather_interactive_config(
            profile=profile,
            runtime=runtime,
            install_os_deps=install_os,
            with_postgres=with_pg,
        )

    print_banner()
    prof = profile or "demo"
    rt: RuntimeMode = runtime or "manual"  # type: ignore[assignment]
    os_deps = bool(args.install_os_deps)
    pg = bool(args.with_postgres)
    if pg and not docker_available():
        print("WARNING: --with-postgres set but Docker is not available; skipping Postgres container.")
        pg = False
    return prof, rt, os_deps, pg


def apply_runtime(
    pack: Path,
    runtime: RuntimeMode,
    *,
    dry_run: bool,
    skip_frontend: bool,
) -> None:
    if runtime == "none":
        return
    if runtime == "systemd":
        if skip_frontend:
            raise SystemExit("systemd runtime requires frontend (omit --skip-frontend).")
        install_systemd_user_units(pack, dry_run=dry_run)
        return
    if runtime == "docker":
        start_docker_compose_stack(pack, dry_run=dry_run)
        return
    py = pack / ".venv" / "bin" / "python"
    print(
        "Runtime=manual: start API + UI yourself when ready.\n"
        f"  Example API:  set -a && source .env && set +a && "
        f"PYTHONPATH=backend/change-society-service/src "
        f"{py} -m uvicorn change_society.main:app --host 127.0.0.1 --port 32500"
    )


def main() -> int:
    args = parse_args()
    profile, runtime, install_os_deps, with_postgres = resolve_config(args)

    if profile == "production":
        print_banner()
        production_hints()
        return 0

    check_python()
    pack = pack_root()
    requirements = pack / "requirements.txt"
    if not requirements.is_file():
        requirements = pack / "backend" / "change-society-service" / "requirements.txt"
    frontend = pack / "frontend"
    env_path = pack / ".env"

    if not requirements.is_file():
        raise SystemExit(f"Missing {requirements}")

    print(f"Pack root: {pack}")
    print(
        f"Profile: {profile}  Runtime: {runtime}  OS deps: {install_os_deps}  "
        f"Postgres container: {with_postgres}"
    )

    install_os_dependencies(
        install_os_deps=install_os_deps,
        runtime=runtime,
        skip_frontend=args.skip_frontend,
        dry_run=args.dry_run,
    )

    python = ensure_venv(pack, args.dry_run)
    install_backend(python, requirements, args.dry_run)
    dev_requirements = pack / "requirements-dev.txt"
    if dev_requirements.is_file():
        install_backend(python, dev_requirements, args.dry_run)
    install_frontend(frontend, args.dry_run, args.skip_frontend)
    ensure_demo_env(env_path, args.dry_run)

    if with_postgres:
        start_docker_postgres(pack, dry_run=args.dry_run)

    apply_runtime(
        pack,
        runtime,
        dry_run=args.dry_run,
        skip_frontend=args.skip_frontend,
    )

    if profile == "verify":
        run_verify(pack, args.dry_run)

    print(narrative_for_runtime(runtime))
    print(
        "Install does NOT: create Qwen Cloud accounts, inject production secrets, deploy Alibaba ECS.\n"
        "See docs/07-deployment-and-operations.md for production compose."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
